language: python
python:
  - "3.5"

# Install dependencies
install:
  - pip install -r requirements.txt
  - git clone https://github.com/rhjdjong/SlipLib.git
  - pip install SlipLib

# Run tests
script:
  - "flake8 --exclude .venv/,docs/,SlipLib/ ."
  - pytest tests/
