sudo: required
dist: trusty

language: python
python:
  - "3.5"

# Install dependencies
install:
  - pip3 install -r requirements.txt

# Run tests
script:
  - flake8 --exclude docs/ .
#  - pytest --ignore=tests/test_tun.py tests/
  - sudo ~/virtualenv/python3.5/bin/python3 -m "pytest tests/"
