language: python
python:
  - "3.5"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests
script:
  - "flake8 --exclude .venv/,docs/,tests/test_tun.py ."
  - pytest --ignore=tests/test_tun.py tests/
